artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://github.com/priyamalik321/I_Phone_webscraping/raw/main/wine.zip"
  local_data_file: artifacts/data_ingestion/Wine.zip
  unzip_dir: artifacts/data_ingestion
